version: '3'
volumes:
  php-fpm-socket:
  db-volume:
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
        - "8080:80"
    environment: 
      - DOC_PUBLIC_ROOT=${DOC_PUBLIC_ROOT:-/var/www/app/public}
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./src
        target: ${DOC_ROOT:-/var/www/html/app}
      - type: bind
        source: ./web/templates
        target: /etc/nginx/templates
  php:
    working_dir: ${DOC_ROOT:-/var/www/html/app}
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./src
        target: ${DOC_ROOT:-/var/www/html/app}
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME:-sample}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-user}
    command: --default-authentication-plugin=mysql_native_password --group-concat-max-len=30000
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: db-volume
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: ./db/sql 
        target: /docker-entrypoint-initdb.d